apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: approute
  namespace: default
  labels:
    app: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qa.devpie.io`)
      kind: Rule
      services:
        - name: spa-client-svc
          port: 80
    - match: Host(`qa.devpie.io`) && PathPrefix(`/api/v1/projects`)
      kind: Rule
      services:
        - name: mic-projects-svc
          port: 4020
    - match: Host(`qa.devpie.io`) && PathPrefix(`/api/v1/users`)
      kind: Rule
      services:
        - name: app-identity-svc
          port: 4000
    - match: Host(`qa.devpie.io`) && PathPrefix(`/api/v1/accounting`)
      kind: Rule
      services:
        - name: app-accounting-svc
          port: 4010
