# apiVersion: v1
# kind: Secret
# metadata:
#   name: secrets
# data:
#   auth0-domain: ==== base64 encoded credential ====
#   auth0-audience: ==== base64 encoded credential ====
#   auth0-client-id: ==== base64 encoded credential ====

#   auth0-client-id: ==== base64 encoded credential ====

#   aws-s3-bucket: ==== base64 encoded credential ====
#   aws-cognito-identity: ==== base64 encoded credential ====

#   freshbooks-client-id: ==== base64 encoded credential ====
#   freshbooks-client-secret: ==== base64 encoded credential ====

#   qa-view-db-identity-host: ==== base64 encoded credential ====
#   qa-view-db-identity-database-name: ==== base64 encoded credential ====
#   qa-view-db-identity-username: ==== base64 encoded credential ====
#   qa-view-db-identity-password: ==== base64 encoded credential ====
#   qa-view-db-identity-url: ==== base64 encoded credential ====

#   qa-mic-db-identity-host: ==== base64 encoded credential ====
#   qa-mic-db-identity-database-name: ==== base64 encoded credential ====
#   qa-mic-db-identity-username: ==== base64 encoded credential ====
#   qa-mic-db-identity-password: ==== base64 encoded credential ====

#   qa-mic-db-projects-host: ==== base64 encoded credential ====
#   qa-mic-db-projects-database-name: ==== base64 encoded credential ====
#   qa-mic-db-projects-username: ==== base64 encoded credential ====
#   qa-mic-db-projects-password: ==== base64 encoded credential ====
#   qa-mic-db-projects-url: ==== base64 encoded credential ====

#   qa-mic-db-identity-url: ==== base64 encoded credential ====
#   qa-msg-db-nats-host: ==== base64 encoded credential ====
#   qa-msg-db-nats-database-name: ==== base64 encoded credential ====
#   qa-msg-db-nats-username: ==== base64 encoded credential ====
#   qa-msg-db-nats-password: ==== base64 encoded credential ====
#   qa-msg-db-nats-port: ==== base64 encoded credential ====
#   qa-msg-db-nats-url: ==== base64 encoded credential ====

#   mic-auth0-auth-domain: ==== base64 encoded credential ====
#   mic-auth0-auth-audience: ==== base64 encoded credential ====

